#!/usr/bin/env python3
"""TTF/OTF -> compact vector font header for the device rasteriser (src/vfont.h).

Usage:
  vfont_build.py NAME font.ttf [--wght 600] [--chars STRING] [-o out.h]

Variable fonts are instanced at --wght (fontTools instancer), so one source
file gives us any weight at build time; the device only ever sees static
quadratic outlines. Cubic (CFF) outlines are converted to quadratics.

Output format (all little-endian ints in font units, see src/vfont.h):
  VfGlyph  { adv, xmin, ymin, xmax, ymax, pointOffset, pointCount }
  points   int16 pairs: x = (X << 1) | onCurve, y = (Y << 1) | contourEnd
Every contour is a closed loop of on/off-curve points, TrueType style: two
consecutive off points imply an on point at their midpoint.
"""
import argparse
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen
from fontTools.pens.cu2quPen import Cu2QuPen

DEFAULT_CHARS = (" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                 "[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~·")


class QuadPen(BasePen):
    """Collects closed contours as lists of (x, y, on_curve)."""

    def __init__(self, glyphSet):
        super().__init__(glyphSet)
        self.contours = []
        self._cur = None

    def _moveTo(self, p):
        self._cur = [(p[0], p[1], True)]

    def _lineTo(self, p):
        self._cur.append((p[0], p[1], True))

    def _qCurveToOne(self, c, p):
        self._cur.append((c[0], c[1], False))
        self._cur.append((p[0], p[1], True))

    def _curveToOne(self, c1, c2, p):
        raise RuntimeError("cubic reached QuadPen; wrap in Cu2QuPen")

    def _closePath(self):
        self._flush()

    def _endPath(self):
        self._flush()

    def _flush(self):
        if not self._cur:
            return
        c = self._cur
        # Drop a closing point that duplicates the start.
        if len(c) > 1 and c[-1][0] == c[0][0] and c[-1][1] == c[0][1] and c[-1][2]:
            c.pop()
        if len(c) >= 2:
            self.contours.append(c)
        self._cur = None


def load(path, wght):
    font = TTFont(path)
    if "fvar" in font:
        from fontTools.varLib import instancer
        axes = {a.axisTag: (a.minValue, a.defaultValue, a.maxValue)
                for a in font["fvar"].axes}
        if "wght" not in axes:
            sys.exit("variable font has no wght axis: %s" % list(axes))
        lo, _, hi = axes["wght"]
        if not lo <= wght <= hi:
            sys.exit("wght %d outside [%d, %d]" % (wght, lo, hi))
        font = instancer.instantiateVariableFont(font, {"wght": wght}, inplace=False)
    elif wght is not None:
        print("note: static font, --wght ignored", file=sys.stderr)
    return font


def build(name, path, wght, chars, out):
    font = load(path, wght)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    hhea, os2 = font["hhea"], font["OS/2"]
    cap = getattr(os2, "sCapHeight", 0) or 0

    def rnd(v):
        return int(round(v))

    glyphs, points = [], []
    ranges = []   # contiguous codepoint intervals -> glyph index
    for cp in sorted(set(ord(c) for c in chars)):
        gname = cmap.get(cp)
        if gname is None:
            print("warning: U+%04X missing, using .notdef" % cp, file=sys.stderr)
            gname = ".notdef"
        pen = QuadPen(gs)
        gs[gname].draw(Cu2QuPen(pen, max_err=upm / 1000.0, all_quadratic=True))
        adv = gs[gname].width
        xs = [p[0] for c in pen.contours for p in c] or [0]
        ys = [p[1] for c in pen.contours for p in c] or [0]
        gi = len(glyphs)
        if ranges and ranges[-1][1] + 1 == cp:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, gi])
        off = len(points)
        n = 0
        for c in pen.contours:
            for i, (x, y, on) in enumerate(c):
                X, Y = rnd(x), rnd(y)
                if not -16384 <= X < 16384 or not -16384 <= Y < 16384:
                    sys.exit("coordinate overflow in %s" % gname)
                end = i == len(c) - 1
                points.append(((X << 1) | (1 if on else 0), (Y << 1) | (1 if end else 0)))
                n += 1
        glyphs.append((rnd(adv), rnd(min(xs)), rnd(min(ys)), rnd(max(xs)), rnd(max(ys)), off, n))

    zero = glyphs[chars.index("0")] if "0" in chars else None
    digit_top, digit_bot = (zero[4], zero[2]) if zero else (cap, 0)

    w = out.write
    w("#pragma once\n#include \"vfont.h\"\n")
    w("// Generated by tools/vfont/vfont_build.py — do not edit.\n")
    w("// Source: %s%s\n" % (path.split("/")[-1], "  wght=%d" % wght if wght else ""))
    w("// %d glyphs, %d points (%d bytes of outline data)\n\n"
      % (len(glyphs), len(points), len(points) * 4))
    w("static const int16_t %s_Points[%d] = {\n" % (name, len(points) * 2))
    for i in range(0, len(points), 8):
        w("    " + ", ".join("%d,%d" % p for p in points[i:i + 8]) + ",\n")
    w("};\n\n")
    w("static const VfGlyph %s_Glyphs[%d] = {\n" % (name, len(glyphs)))
    for g in glyphs:
        w("    {%d, %d, %d, %d, %d, %d, %d},\n" % g)
    w("};\n\n")
    w("static const EpdUnicodeInterval %s_Intervals[%d] = {\n" % (name, len(ranges)))
    for r in ranges:
        w("    {%d, %d, %d},\n" % tuple(r))
    w("};\n\n")
    w("const VfFont %s = {\n" % name)
    w("    %d,  // unitsPerEm\n" % upm)
    w("    %d, %d,  // ascender, descender\n" % (hhea.ascent, hhea.descent))
    w("    %d,  // capHeight\n" % cap)
    w("    %d, %d,  // digitTop, digitBottom ('0' ink box)\n" % (digit_top, digit_bot))
    w("    %d, %s_Glyphs, %s_Points,\n" % (len(glyphs), name, name))
    w("    %s_Intervals, %d,\n" % (name, len(ranges)))
    w("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("name")
    ap.add_argument("font")
    ap.add_argument("--wght", type=int, default=None)
    ap.add_argument("--chars", default=DEFAULT_CHARS)
    ap.add_argument("-o", "--out", default="-")
    a = ap.parse_args()
    out = sys.stdout if a.out == "-" else open(a.out, "w")
    build(a.name, a.font, a.wght, a.chars, out)


if __name__ == "__main__":
    main()
