"""Pack a BMP into the 4bpp grey format the e-paper framebuffer uses.

Only the four levels this panel actually renders are used: 0x0 black, 0x3 for
the icon's orange accent (a mid tone, so the two-tone design survives), 0x8 for
soft edges, 0xF white. Anything 0x4 and lighter reads as plain white on this
hardware, which is why the accent cannot simply be "some grey".
"""
import struct, sys

def main(bmp_path, out_path):
    d = open(bmp_path, 'rb').read()
    off = struct.unpack_from('<I', d, 10)[0]
    w, h = struct.unpack_from('<ii', d, 18)
    top_down = h < 0
    h = abs(h)
    stride = w * 4

    def px(x, y):
        row = y if top_down else (h - 1 - y)
        b, g, r, a = d[off + row * stride + x * 4: off + row * stride + x * 4 + 4]
        return r, g, b, a

    def level(p):
        r, g, b, a = p
        if a < 128:
            return 0xF
        lum = 0.299 * r + 0.587 * g + 0.114 * b
        if lum < 90:
            return 0x0
        if r > 150 and r - b > 60:      # orange accent
            return 0x3
        if lum < 200:
            return 0x8
        return 0xF

    packed = bytearray()
    for y in range(h):
        for x in range(0, w, 2):
            hi = level(px(x, y))
            lo = level(px(x + 1, y)) if x + 1 < w else 0xF
            packed.append((lo << 4) | hi)   # low nibble = left pixel

    out = ['// GENERATED by tools/gen_boot_icon.sh — do not edit by hand.',
           '// Source: companion-ios/.../AppIcon-1024.png',
           '//',
           '// 4 bits per pixel, two pixels per byte, low nibble = the left pixel,',
           '// matching epd_draw_pixel. Values are epdiy greys: 0x0 black, 0x3 the',
           '// mid tone standing in for the orange accent, 0xF white.',
           '#pragma once', '#include <cstdint>', '',
           'constexpr int BOOT_ICON_W = %d;' % w,
           'constexpr int BOOT_ICON_H = %d;' % h,
           'const uint8_t kBootIcon[] = {']
    line = '   '
    for b in packed:
        line += ' 0x%02x,' % b
        if len(line) > 74:
            out.append(line); line = '   '
    if line.strip():
        out.append(line)
    out.append('};')
    open(out_path, 'w').write('\n'.join(out) + '\n')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
